### ISSUE TITLE
Could anyone please help me with this issues: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Collection;Ljava/util/Collection;Lcom/facebook/AccessTokenSource;Ljava/util/Date;Ljava/util/Date;)V in class Lcom/facebook/AccessToken; or its super classes (declaration of 'com.facebook.AccessToken'....

### ISSUE THREAD

**Issue by RajiRajah** [parse-community/ParseFacebookUtils-Android#47] opened 2019-02-11 18:23 UTC
I'm working toward allowing user to login via facebook using parse server, the integration was successful but go this error(below) when user is trying to login in.
Please help

02-11 16:33:14.498 20226-20385/com.xpressoftng.betatutor E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-8
                                                                           Process: com.xpressoftng.betatutor, PID: 20226
                                                                           java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Collection;Ljava/util/Collection;Lcom/facebook/AccessTokenSource;Ljava/util/Date;Ljava/util/Date;)V in class Lcom/facebook/AccessToken; or its super classes (declaration of 'com.facebook.AccessToken' appears in /data/app/com.xpressoftng.betatutor-yiEOpIyeFzKdlNn9Dmp8ZA==/split_lib_dependencies_apk.apk)
                                                                               at com.parse.facebook.FacebookController.setAuthData(FacebookController.java:222)
                                                                               at com.parse.facebook.ParseFacebookUtils$1.onRestore(ParseFacebookUtils.java:119)
                                                                               at com.parse.ParseAuthenticationManager$2.call(ParseAuthenticationManager.java:70)
                                                                               at com.parse.ParseAuthenticationManager$2.call(ParseAuthenticationManager.java:67)
                                                                               at bolts.Task$4.run(Task.java:357)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                               at java.lang.Thread.run(Thread.java:764)

**Comment by Jawnnypoo** [comment] 2019-02-11 18:25
Hey there, this is a dupe of https://github.com/parse-community/ParseFacebookUtils-Android/issues/46

**Closed by Jawnnypoo** 2019-02-11 18:25 UTC

**Comment by RajiRajah** [comment] 2019-02-11 18:31
@Jawnnypoo,  have already tried those suggestions, none work for me. 

Please help
